on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch submodules
      run: |
          git submodule update --init  --recursive --depth=1
          ( cd vendor/micropython/ports/unix ; make submodules )
          ( cd vendor/micropython/ports/esp32 ; make submodules )

    - name: Build
      run: |
          rm -rf ./vendor/micropython/mpy-cross/build  # Workaround build failure
          docker run -t -u "$UID:$GID" -e "HOME=/app" -v "${GITHUB_WORKSPACE}:/app" -w "/app" espressif/idf:v5.3.2 make build
      shell: bash

    - name: Upload Main FW Artifacts
      uses: actions/upload-artifact@v4

      with:
        name: firmware
        path: |
          firmware